### ISSUE TITLE
Great gem

### ISSUE THREAD

**Issue by set-pfel** [igorkasyanchuk/avatarro#2]
Is there a way to limit the number of initials?
E.g **J**an **C**laud **J**unker currently gets 3 initials, I would like to limit it to **JJ** (first and last, remove the middle-name).
We also have people with 4 names which results in a weird looking avatar.

**Comment by igorkasyanchuk** [comment]
so you have string "Jan Claud Junker". Just pass "Jan Junker" to it.

This is a pure ruby task, just split the array and take first and last words and join them.
